version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/app

hooks:
  BeforeInstall:
    - location: scripts/stopApp.sh
      runas: root
  AfterInstall:
    - location: scripts/preparation.sh
      runas: root
  ApplicationStart:
    - location: scripts/startApp.sh
      runas: root

permissions:
  - object: /var/www/app/scripts
    pattern: "**"
    owner: ec2-user
    group: nginx
    mode: 774
    type:
      - file
